// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseManifest() {
  return window['go']['main']['App']['ChooseManifest']();
}

export function ConvertMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertMod'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ShowFolderInExplorer(arg1) {
  return window['go']['main']['App']['ShowFolderInExplorer'](arg1);
}
